import { OptionalProps } from '@mikro-orm/core'
import { Entity, Index, ManyToOne, PrimaryKey, Property, Unique } from '@mikro-orm/decorators/legacy'

/**
 * A company order — the app-owned root record of one deal.
 *
 * It stores the deal's own header: its number, the operator's title, the order/ETA dates, a status
 * marker and notes. It deliberately holds **no** customer, currency, amount or line data: those stay
 * on the real documents (the installed `sales` orders and this app's `purchasing` orders), which the
 * link table below attaches. The module keeps no ORM relation to any of them — a scalar id plus a
 * frozen snapshot is the platform's durable-reference pattern, and the peer's own tables must never
 * be imported here.
 */
@Entity({ tableName: 'order_hub_company_orders' })
@Unique({ name: 'order_hub_company_orders_scope_number_uniq', properties: ['tenantId', 'organizationId', 'number'] })
// The workbench lists a company order's own organization, newest first: the common filter leads with
// the scope columns and ends on the sort column.
@Index({ name: 'order_hub_company_orders_scope_idx', properties: ['organizationId', 'tenantId', 'createdAt'] })
export class CompanyOrder {
  [OptionalProps]?: 'status' | 'createdAt' | 'updatedAt'

  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string

  @Property({ name: 'tenant_id', type: 'uuid' })
  tenantId!: string

  @Property({ name: 'organization_id', type: 'uuid' })
  organizationId!: string

  /** `CO-<year>-<4 digits>`, generated by the create command under the unique key above. */
  @Property({ type: 'text' })
  number!: string

  @Property({ type: 'text', nullable: true })
  title?: string | null

  @Property({ name: 'order_date', type: 'date' })
  orderDate!: Date

  @Property({ name: 'eta_date', type: 'date', nullable: true })
  etaDate?: Date | null

  /** One of the module constants (`draft`/`in_progress`/`completed`/`cancelled`); a marker, not a dictionary. */
  @Property({ type: 'text', default: 'draft' })
  status: string = 'draft'

  @Property({ type: 'text', nullable: true })
  notes?: string | null

  /**
   * The optional default customer of the deal: a scalar `parties` id plus the display name frozen
   * at write time (the party's own `name` is encrypted, so the hub never re-reads it). Omitted at
   * create is `null`; an explicit `null` in an update clears it — an absent key never does (the
   * partial-update rule). Buyer side of the deal.
   */
  @Property({ name: 'customer_party_id', type: 'uuid', nullable: true })
  customerPartyId?: string | null

  /** `{ name, code }` frozen at write time; see `customerPartyId`. */
  @Property({ name: 'customer_snapshot', type: 'jsonb', nullable: true })
  customerSnapshot?: Record<string, unknown> | null

  /**
   * The optional default supplier: a scalar `purchasing_suppliers` id plus its frozen name
   * snapshot, the counterpart pair to `customerPartyId`.
   */
  @Property({ name: 'supplier_id', type: 'uuid', nullable: true })
  supplierId?: string | null

  /** `{ name, code }` frozen at write time; see `supplierId`. */
  @Property({ name: 'supplier_snapshot', type: 'jsonb', nullable: true })
  supplierSnapshot?: Record<string, unknown> | null

  @Property({ name: 'created_at', type: Date, onCreate: () => new Date() })
  createdAt: Date = new Date()

  @Property({ name: 'updated_at', type: Date, onCreate: () => new Date(), onUpdate: () => new Date() })
  updatedAt: Date = new Date()

  @Property({ name: 'deleted_at', type: Date, nullable: true })
  deletedAt?: Date | null
}

/**
 * One child document attached to a company order.
 *
 * `kind` names which module owns the document — `internal_sales_order` / `external_sales_order`
 * (both live in the installed `sales_orders`) or `purchase_order` (this app's `purchasing`). The
 * relation to the company order is the only ORM relation, and it cascades: deleting the root drops
 * its links. The peer is a scalar id plus a **frozen** display snapshot (`refNumber`,
 * `refCounterparty`, `refSnapshot`): renaming or deleting the peer never rewrites what the hub
 * printed. The unique key makes an attach idempotent; the reverse index answers "which company order
 * holds this document".
 */
@Entity({ tableName: 'order_hub_company_order_links' })
@Unique({ name: 'order_hub_company_order_links_order_kind_ref_uniq', properties: ['companyOrder', 'kind', 'refId'] })
@Index({ name: 'order_hub_company_order_links_scope_ref_idx', properties: ['organizationId', 'tenantId', 'refId'] })
export class CompanyOrderLink {
  [OptionalProps]?: 'createdAt' | 'updatedAt'

  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string

  @Property({ name: 'tenant_id', type: 'uuid' })
  tenantId!: string

  @Property({ name: 'organization_id', type: 'uuid' })
  organizationId!: string

  @ManyToOne(() => CompanyOrder, { fieldName: 'company_order_id', deleteRule: 'cascade' })
  companyOrder!: CompanyOrder

  /** `internal_sales_order` | `external_sales_order` | `purchase_order`; see `data/validators.ts`. */
  @Property({ name: 'kind', type: 'text' })
  kind!: string

  @Property({ name: 'ref_id', type: 'uuid' })
  refId!: string

  /** The peer's business number, frozen at link time. */
  @Property({ name: 'ref_number', type: 'text', nullable: true })
  refNumber?: string | null

  /** The peer's counterparty display name, frozen at link time. */
  @Property({ name: 'ref_counterparty', type: 'text', nullable: true })
  refCounterparty?: string | null

  /** `{ status, createdAt, currencyCode, totalGross }`, frozen at link time. */
  @Property({ name: 'ref_snapshot', type: 'jsonb', nullable: true })
  refSnapshot?: Record<string, unknown> | null

  @Property({ name: 'created_at', type: Date, onCreate: () => new Date() })
  createdAt: Date = new Date()

  @Property({ name: 'updated_at', type: Date, onCreate: () => new Date(), onUpdate: () => new Date() })
  updatedAt: Date = new Date()
}

/**
 * One **collaborating organization** of a company order (REQ-014).
 *
 * The owner organization writes this set; each row grants exactly one other organization the right
 * to *see* the root in its own workbench and to write its `status`/`notes` (and nothing else — the
 * whitelist lives in the update command, not here). Unlike `CompanyOrderLink`, the row's
 * `organizationId` is the **collaborator**, not the root's owner, so the reverse index leads with it:
 * "which roots do I collaborate on" is the read the list/stage scope widens with.
 *
 * The pair is unique per root: re-adding an organization collapses onto the same row (the replace
 * command de-duplicates before the index sees it).
 */
@Entity({ tableName: 'order_hub_company_order_collaborators' })
@Unique({
  name: 'order_hub_company_order_collaborators_order_org_uniq',
  properties: ['companyOrder', 'organizationId'],
})
@Index({ name: 'order_hub_company_order_collaborators_scope_idx', properties: ['organizationId', 'tenantId'] })
export class CompanyOrderCollaborator {
  [OptionalProps]?: 'createdAt' | 'updatedAt'

  @PrimaryKey({ type: 'uuid', defaultRaw: 'gen_random_uuid()' })
  id!: string

  @Property({ name: 'tenant_id', type: 'uuid' })
  tenantId!: string

  /** The **collaborating** organization; the root's own `organization_id` never appears here. */
  @Property({ name: 'organization_id', type: 'uuid' })
  organizationId!: string

  @ManyToOne(() => CompanyOrder, { fieldName: 'company_order_id', deleteRule: 'cascade' })
  companyOrder!: CompanyOrder

  @Property({ name: 'created_at', type: Date, onCreate: () => new Date() })
  createdAt: Date = new Date()

  @Property({ name: 'updated_at', type: Date, onCreate: () => new Date(), onUpdate: () => new Date() })
  updatedAt: Date = new Date()
}
