import { Migration } from '@mikro-orm/migrations';

/**
 * Adds the library row's discount percent.
 *
 * Filed in `sourcing`, not in `purchasing` where the entity lives: the module chains run in
 * module-id order, `purchasing` is applied *before* `sourcing`, and `purchasing_supplier_products` is
 * created and renamed inside `sourcing`'s chain — a `purchasing`-filed statement runs against a table
 * that does not exist yet on a fresh database. See the lesson
 * `.ai/lessons/cross-module-rename-migration-ordering.md` (this file was generated by `db:generate`
 * next to its products sibling and moved here for that reason).
 */
export class Migration20260924031334_sourcing extends Migration {

  override name = 'Migration20260924031334';

  override up(): void | Promise<void> {
    this.addSql(`alter table "purchasing_supplier_products" add "discount_percent" numeric(7,4) null;`);
  }

  override down(): void | Promise<void> {
    this.addSql(`alter table "purchasing_supplier_products" drop column "discount_percent";`);
  }

}
